export default function randomWord() {
    const randomIndex = Math.floor(Math.random() * gameWords.length)
    const gameWord = gameWords[randomIndex];
      // console.log("Selected word:", gameWord);
    return gameWord
    
}
export const gameWords = [
  "play", "jump", "duck", "wave", "milk", "book", "song", "rain", "fire", "snow",
  "wind", "star", "cake", "fish", "leaf", "door", "shoe", "bear", "frog", "ship",
  "apple", "chair", "light", "sweet", "beach", "grass", "smile", "water", "cloud",
  "sugar", "house", "paint", "jelly", "grape", "spice", "music", "tiger", "toast",
  "lemon", "puppy", "heart", "candy", "magic", "zebra", "drink", "mouse", "bread",
  "banana", "orange", "coffee", "castle", "cookie", "forest", "rocket", "bottle",
  "silver", "breeze", "pillow", "dragon", "mirror", "planet", "pepper", "rabbit",
  "sunset", "wizard", "travel", "butter", "stream", "parrot", "marble", "smooth",
  "cotton", "pumpkin", "giraffe", "firefly", "blanket", "diamond", "glasses",
  "penguin", "cupcake", "sparkle", "biscuit", "rainbow", "monster", "village",
  "tornado", "unicorn", "sandals", "balloon", "journey", "perfume", "sandbag",
  "butterfly", "sunshine", "elephant", "chocolate", "notebook", "umbrella",
  "football", "calendar", "avocado", "necklace", "mountain", "strawberry",
  "treasure", "popcorn", "campfire", "pineapple", "adventure", "waterfall",
  "blueberry", "snowflake", "playground", "sunflower", "lullabies", "happiness",
  "cactus", "pencil", "planet", "mirror", "button", "rabbit", "cookie", "ocean",
  "shower", "garden", "flower", "island", "beacon", "jungle", "bridge", "candle",
  "camera", "butter", "stream", "breeze", "window", "rocket", "silver", "fluffy",
  "pocket", "pepper", "forest", "castle", "circle", "school", "friend", "basket",
  "parrot", "orange", "carpet", "sunset", "wizard", "flight", "guitar", "pillow",
  "monkey", "travel", "bottle", "smooth", "cloudy", "energy", "gentle", "hidden",
  "bright", "golden", "hollow", "pretty", "little", "shiny", "purple", "family",
  "granny", "spark", "brave", "crazy", "dream", "flame", "laugh", "peace",
  "queen", "river", "smile", "table", "tasty", "trick", "witty", "youth",
  "angel", "bloom", "charm", "fancy", "honey", "juice", "light", "merry", "pearl",
  "quiet", "roses", "spice", "sweet", "treat", "vibes", "zesty", "amber", "bingo",
  "climb", "dance", "earth", "flour", "grape", "house", "lemon", "music", "peach",
  "swing", "toast", "watch", "zebra", "board", "chess", "dress", "frost", "green",
  "hatch", "knife", "melon", "noble", "oasis", "paint", "quack", "ridge", "scent",
  "socks", "train", "vocal", "wheat", "yacht", "bliss", "candy", "daisy", "elbow",
  "flame", "grill", "honor", "icily", "jewel", "koala", "lucky", "maple", "novel",
  "olive", "plush", "queen", "rider", "sandy", "thick", "urban", "valve", "witty",
  "young", "zippy", "anchor", "butter", "carrot", "donkey", "energy", "feather",
  "giggle", "hammer", "island", "jungle", "kitten", "laptop", "marble", "napkin",
  "outfit", "pocket", "quartz", "ribbon", "sunset", "tunnel", "violet", "wallet",
  "zipper", "balance", "captain", "delight", "emerald", "fortune", "holiday",
  "journey", "kingdom", "lantern", "morning", "nuggets", "octagon", "picture",
  "rainbow", "station", "trouble", "upgrade", "villain", "welcome", "balloon",
  "cowgirl", "diamond", "festival", "garment", "harvest", "iceberg", "jewelry",
  "kitchen", "library", "monster", "network", "orchard", "perfume", "pumpkin",
  "recycle", "skylark", "teacher", "unicorn", "village", "warrior", "zucchini",
  "avocado", "backpack", "bluebird", "cherries", "cowbells", "daydream",
  "elevator", "fireball", "handmade", "jacketed", "ladybird", "pinecone",
  "popcorn", "racecars", "snapshot", "sparkler", "wildlife", "starlight",
  "puzzle", "gravel", "marsh", "piano", "docks", "blaze", "minty", "crisp",
  "trail", "scoop", "spoon", "gleam", "vivid", "frost", "tunes", "glide",
  "fuzzy", "socks", "rains", "hints", "glows", "paint", "flock", "crane",
  "nurse", "ocean", "plume", "spine", "trend", "wagon", "yummy", "tiger",
  "gloom", "daisy", "blink", "cheer", "grins", "bluff", "dream", "waves",
  "ridge", "miles", "hobby", "hills", "creek", "trout", "bacon", "toast",
  "noisy", "quiet", "tempo", "swift", "magic", "bunny", "jolly", "queen",
  "angel", "hiker", "crown", "flair", "pearl", "sugar", "lemon", "sweet",
  "fable", "diner", "story", "pouch", "brace", "sandy", "shiny", "vivid",
  "amber", "berry", "coral", "dusty", "elder", "fauna", "ghost", "happy",
  "inlet", "jumpy", "karma", "linen", "mango", "nifty", "onion", "plaza",
  "quota", "rumor", "savor", "tango", "urban", "vapor", "whale", "youth",
  "zesty", "replace", "concat", "clone", "assign", "bind", "apply", "call", "match",
  "test", "exec", "check", "verify", "secure", "access", "token", "login",
  "logout", "signup", "account", "profile", "avatar", "follow", "unfollow",
  "like", "share", "comment", "post", "tweet", "reply", "update", "upload",
  "save", "draft", "delete", "remove", "clear", "reset", "refresh", "reload"
];
